const { writeFileSync } = require("fs");
const { resolve } = require("path");
const dir = resolve(`${__dirname}/../`);
writeFileSync(`${dir}/dark.js`, "\n\
const { JSX } = require(\"typedoc\");\n\
\n\
// https://github.com/TypeStrong/typedoc/issues/1840#issuecomment-1012736455\n\
exports.load = function load(app) {\n\
	app.renderer.hooks.on(\"head.begin\", () => {\n\
		return JSX.createElement(\"script\", null,\n\
		JSX.createElement(JSX.Raw, { html: \"localStorage.setItem('tsd-theme', localStorage.getItem('tsd-theme') || 'dark')\" }));\n\
	});\n\
}");
	// note for anyone changing this, this does not affect the docs on https://docs.oceanic.ws
	// this only effects the test workflow - let Donovan know if something needs to change here
writeFileSync(`${dir}/typedoc.json`, JSON.stringify({
	name:        "Oceanic",
	entryPoints: [
		"lib/"
	],
	plugin: [
		"typedoc-plugin-rename-defaults",
		"typedoc-plugin-extras",
		`${dir}/dark.js`
	],
	tsconfig:           "tsconfig.json",
	entryPointStrategy: "expand",
	excludePrivate:     true,
	excludeProtected:   true,
	githubPages:        false,
	hideGenerator:      true,
	gitRemote:          "origin",
	readme:             "README.md",
	out:                "docs",
	exclude:            [],
	favicon: "favicon.ico"
}));
writeFileSync(`${dir}/favicon.ico`, Buffer.from("AAABAAEAIBUAAAEAIAD8CgAAFgAAACgAAAAgAAAAKgAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADcbAACZUCpKmVAqnplQKsyZUCrMmVAqnplQKkoYDxMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZUCoemVAqwJlQKv+ZUCr/mVAq/5lQKv+ZUCr/mVAq/5lQKsCZUCoeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmVAqEJlQKuCZUCr/mVAq/5lQKv+ZUCr/mVAq/5lQKv+ZUCr/mVAq/5lQKuCZUCoQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZUCqgmVAq/5lQKv+ZUCrRp2Mqcb6AK2q7fCtvmVAqiplQKvWZUCr/mVAq/5lQKqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmVAqFJlQKv2ZUCr/mVAqs9ebLIjaniz32p4s/9qeLP/anizYvX8raZlQKvSZUCr/mVAq/ZlQKhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZUCpSmVAq/5lQKvPSlSx22p4s9tqeLK3aniyZ2p4s3dqeLMXaniyPn1kqgplQKv+ZUCr/mVAqUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJlQKmaZUCr/mVAqp9qeLKzaniwjAAAAAAAAAADbnisCmVAqiJlQKsCZUCpOmVAq/5lQKv+ZUCpmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmVAqUplQKv+ZUCqX2p4sSgAAAAAAAAAAAAAAAAAAAACZUCr/mVAq/5lQKraZUCr/mVAq/5lQKkQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZUCoUmVAq/ZlQKqcDAwAAAAAAAAAAAAAAAAAAAAAAAJlQKrmZUCr/mVAq/plQKv+ZUCqoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZUCqhmVAq75lQKgsAAAAAVzwLANqeLKXaniyxvn8rFZlQKmmZUCqTpmMqYtqeLDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJlQKhGZUCrgmVAqigAAAADaniwk2p4s/9qeLP/aniym2p4s8dqeLNPanizg2p4sEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJlQKh+ZUCrFmVAqadygKwDanizX2p4s/9qeLP/aniz/2p4sxtqeLB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJpPLACZUCpPmVAqVMOGKxvanixs2p4sg9qeLEjani0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////////////gf///gB///wAP//8AD//+AAf//gAH//4MB//+Hgf//j4P//8YD///EA///4gf///gf//////////////////////8=", "base64"));
