name: Publish Dev Version
permissions:
  contents: read
  id-token: write
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    uses: ./.github/workflows/lint.yml
  publish:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Update NPM # Needed for provenance
        run: npm i -g npm@"^9.5"

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Set Version
        run: |
          pnpm version --no-git-tag-version patch
          hash=$(git rev-parse --short dev)
          version=$(jq -r .version package.json)
          v="$version-dev.$hash"
          echo "Setting Version: $v"
          contents=$(jq --arg version "$v" '.version = $version' package.json) && echo -E "${contents}" > package.json

      - name: Publish
        run: pnpm publish --provenance --no-git-checks --tag dev --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deprecate Old Versions
        run: npx -y npm-deprecate
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
