name: Build Docs
permissions:
  contents: read
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Test Docs
        run: pnpm run test:docs
